# Generated by Django 5.1.2 on 2025-01-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_session_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
