# Generated by Django 5.1.2 on 2025-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('number', 'course'), name='unique_session_per_course'),
        ),
    ]
